version: 1.1.0.{build}.{branch}

init:
  - git config --global core.autocrlf true

before_build:
 - cmd: dotnet restore SudokuSolver.sln

build_script:
 - cmd: dotnet build SudokuSolver.sln
 - cmd: dotnet publish SudokuSolver.App

artifacts:
 - path: '\SudokuSolver.App\bin\Debug\netcoreapp1.1'
   name: App
   type: ConsoleApp

test_script:
 - ps: cd .\SudokuSolver.UnitTest
 - cmd: dotnet test
 - ps: cd ..\SudokuSolver.App
 - cmd: dotnet exec bin\Debug\netcoreapp1.1\SudokuSolver.App.dll